export const SEQUELIZE = 'SEQUELIZE';
export const EXPERTISE_REPOSITORY = 'EXPERTISE_REPOSITORY';
export const MEDIC_INFOS_REPOSITORY = 'MEDIC_INFO_REPOSITORY';
export const MEDIC_WORK_REPOSITORY = 'MEDIC_WORK_REPOSITORY';
